name: Enviar correo diario

on:
  schedule:
    - cron: "30 10 * * *"   # 07:30 en Chile (UTC-3 o UTC-4 según DST)
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai

      - name: Run script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python send_email.py

